docs: add documentation for model caching on RunPod
runpod/docs pull request #135
Opened 2024-08-09 21:49 UTC by rachfop

2024-08-12 14:10 UTC, maglietti requested changes
The doc is missing instructions about how to access the cached models from inside the container. 

Lets. collaborate on this one.

2024-09-12 15:06 UTC, Yhlong00 approved these changes

2024-10-30 21:59 UTC, Yhlong00 commented
1. I was under the impression that model caching was specific to vLLM?
2. If users are working with a network volume, would model caching still be necessary? Or config model cache can cache the model on GPU server?
3. It might be helpful to provide an example of a model that uses a specific branch.

2024-10-30 22:19 UTC, TimPietruskyRunPod requested changes
There are some parts missing related how the modelcache works. I tried to explain everything, please let me know if something is not clear.

2024-10-30 22:19 UTC, TimPietruskyRunPod commented on docs/pods/storage/model-caching.md
> +## Using Network Volumes
all of this has nothing to do with the modelcache, as it behaves out of the users scope. no network volume is needed.

instead we would need to know where the files are actually available after the container is starting:

* modelcache downloads the models / datasets from huggingface
* only when this is done, the pod / worker can actually start and execute what ever their purpose is (like running ComfyUI or doing inference for an LLM)
* the model is mounted read-only in `/runpod/cache/model/<organization>/<repo>/<branch>`
* users can then use the model / dataset inside their project and don't have to bake models into docker images anymore
* public models are shared with all users in the same datacenter
* private models can only be accessed by users who have access to the repo using their `RUNPOD_HUGGINGFACE_USER` + RUNPOD_HUGGINGFACE_TOKEN`. we always check the auth when users try to access this model. the model can then be found at `/runpod/cache/model/<user>/<organization>/<repo>/<branch>`

2024-10-30 22:32 UTC, TimPietruskyRunPod commented
@Yhlong00 

> 1. I was under the impression that model caching was specific to vLLM?
nope, works with anything. 

> 2. If users are working with a network volume, would model caching still be necessary? Or config model cache can cache the model on GPU server?
yes, because you are not forced to stay in a specific datacenter, as you are not bound to a network volume. 

> 3. It might be helpful to provide an example of a model that uses a specific branch.
totally: `RUNPOD_HUGGINGFACE_MODEL`: `stabilityai/stable-diffusion-3.5-medium/feat-quantization`

2024-11-12 21:15 UTC, closed without merging