Open ai
runpod/docs pull request #49
Opened 2024-02-22 22:08 UTC by rachfop

2024-03-04 07:30 UTC, sumo43 approved these changes
LGTM

2024-03-06 00:05 UTC, alpayariyak requested changes
I don't have access to Vercel, so these were some comments based on the raw markdown

2024-03-06 00:05 UTC, alpayariyak commented on docs/serverless/workers/vllm/openai-compatibility.md
There's no `model:tag` naming - `MODEL_NAME` is the hugginface repo of the model

For an Endpoint ID abc, the syntax in the tutorial will result in .../v2/$abc/openai/v1, so $ needs to be removed. Same for the tutorial in get-started if it's copied. Also a page for non-openai is missing

2024-03-14 21:43 UTC, AllysonRosenthal commented on docs/serverless/endpoints/overview.md
> +- **Asynchronous and synchronous Jobs:** Choose the execution mode that best fits your workflow, whether it's a task that runs in the background or one that delivers immediate results.
Should jobs also be lowercase?

2024-03-14 21:44 UTC, AllysonRosenthal commented on docs/serverless/endpoints/overview.md
> +**Privacy and Security:** RunPod prioritizes your data's privacy and security.
Why is security capitalized here?

2024-03-14 22:42 UTC, AllysonRosenthal reviewed
Partial review. I've gotten through changed files through vllm/get-started. The Getting Started page has comments in Vercel, the rest are here.

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +| `BASE_PATH`         | `/runpod-volume` | `str`                                                     | Storage directory for Huggingface cache and model. Utilizes network storage if attached when poi
Huggingface -> Hugging Face 

Confusing description. Maybe something like:
When network storage is attached, uses a single Worker to download the model once for all Workers to load. If no network storage is present, creates a local directory within each Worker and downloads the model for each.

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +| `MAX_PARALLEL_LOADING_WORKERS` | `None`  | `int`            | Load model sequentially in multiple batches, to avoid RAM OOM when using tensor parallel and large models.                          |
Load -> loads, remove comma

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +| `ENFORCE_EAGER`                | `0`     | boolean as `int` | Always use eager-mode PyTorch. If False(`0`), will use eager mode and CUDA graph in hybrid for maximal performance and flexibility. |
will use -> uses

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +| `MAX_CONTEXT_LEN_TO_CAPTURE`   | `8192`  | `int`            | Maximum context length covered by CUDA graphs. When a sequence has context length larger than this, we fall back to eager mode.     |
we fall -> ~we~ falls

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +| `DISABLE_CUSTOM_ALL_REDUCE`    | `0`     | `int`            | Enables or disables custom all reduce.                                                                                              |
is "custom all reduce" common knowledge?

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +The first request will have a batch size of `DEFAULT_MIN_BATCH_SIZE`, and each subsequent request will have a batch size of `previous_batch_size * DEFAULT_BATCH_SIZE_GROWTH_FACTOR`.
will have -> uses x2

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +This will continue until the batch size reaches `DEFAULT_BATCH_SIZE`.
will continue -> continues

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +For example, the default values, the batch sizes will be `1, 3, 9, 27, 50, 50, 50, ...`.
using the default values

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +This has nothing to do with vLLM's internal batching, but rather the number of tokens sent in each HTTP request from the worker.
worker -> Worker

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +| `RAW_OPENAI_OUTPUT`                 | `1`         | boolean as `int` | Enables raw OpenAI SSE format string output when streaming. Required to be enabled (which it is by default) for OpenAI compati
Required to be -> must be

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +| `OPENAI_SERVED_MODEL_NAME_OVERRIDE` | `None`      | `str`            | Overrides the name of the served model from model repo/path to specified name, which you will then be able to use the value fo
you will then be able to -> you can

Clarify whether you mean
use the value for -> use as the value for/use the value as 
or something else

2024-03-14 22:42 UTC, AllysonRosenthal commented on docs/serverless/workers/vllm/environment-variables.md
> +| `MAX_CONCURRENCY`      | `300`   | `int`            | Max concurrent requests per worker. vLLM has an internal queue, so you don't have to worry about limiting by VRAM, this is for improving scalin
VRAM, this is for improving -> VRAM. This improves 

And add period at the end of the description.

2024-03-17 16:23 UTC, merged